swagger: "2.0"

info:
  title: Maintenance Task API
  description: Maintenance Task REST API
  version: 1.0

host: localhost
basePath: /api
schemes:
  - http
  - https

definitions:
  _embedded:
    type: object
    properties:
      $ref: '#/definitions/MaintenanceTaskList'

  maintenanceTaskList:
    type: array
    items:
      $ref: '#/definitions/MaintenanceTask'

  MaintenanceTask:
    type: object
    properties:
      id:
        type: integer
        description: The task ID
        example: 151
      deviceId:
        type: integer
        description: The ID of the device this task is tied to
        example: 4
      status:
        type: string
        description: The status of the task (OPEN or CLOSED)
        example: OPEN
      severity:
        type: string
        description: The severity of the task. UNIMPORTANT, IMPORTANT, or CRITICAL.
        example: CRITICAL
      description:
        type: string
        description: The description of the task
        example: Fix CPU overheating problem
      registered:
        type: string
        description: Datetime string, registration time for the task
        example: 2022-08-28T17:32:11.058674

  MaintenanceTaskResponse:
    type: object
    properties:
      $ref: '#/definitions/MaintenanceTask'
      _links:
        type: object:
          schema:
            $ref: '#/definitions/MaintenanceTaskLinks'

  MaintenanceTaskLinks:
    type: object
      properties:
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  description: Hyperlink to this task
                  example: http://localhost:8080/api/tasks/733
            tasks:
              type: object
              properties:
                href:
                  type: string
                  description: Hyperlink to the API endpoint that retrieves all tasks
                  example: http://localhost:8080/api/tasks
            deviceId:
              type: object
              properties:
                href:
                  type: string
                  description: Hyperlink to the API endpoint that retrieves all the tasks for this task's attached device
                  example: http://localhost:8080/api/tasks/deviceId/1
paths:
  /tasks:
    get:
      summary: Returns a list of maintenance tasks
      produces: application/json
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/definitions/maintenanceTaskList'

  /tasks/{taskId}:
    get:
      summary: Returns a single task based on the given ID
      produces: application/json
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: integer
            minimum: 1
          description: The task ID
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/definitions/MaintenanceTask'
        404:
          description: Task not found
    put:
      summary: Modifies a single task based on the given ID
      parameters:
        - in: body
          schema:
            $ref: '#/definitions/MaintenanceTask'
          required:
            - id
            - deviceId
            - description
            - status
            - severity
      consumes: application/json
      produces: application/json
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/definitions/MaintenanceTask'
        404:
          description: Task not found
        404:
          description: Factory device not found
        400:
          description: Bad request
    delete:
      summary: Deletes the specified task
      produces: application/json
      responses:
        200:
          description: OK
        404:
          description: Task not found

  /tasks/create:
    post:
      summary: Creates a new maintenance task
      consumes: application/json
      produces: application/json
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/definitions/MaintenanceTask'
        404:
          description: Factory device not found
  
  /tasks/device/{deviceId}:
    parameters:
      - in: path
        name: deviceId
        required: true
        schema:
          type: integer
          minimum: 1
        description: The device ID
    
    get:
      summary: Retrieves all the tasks associated with this device
      produces: application/jso
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/definitions/maintenanceTaskList'
