swagger: "2.0"

info:
  title: Maintenance Task API
  description: Maintenance Task REST API
  version: 1.0

host: localhost

definitions:
  MaintenanceTaskListResponse:
    type: object
    properties:
      _embedded:
        type: object
        properties:
          maintenanceTaskList:
            type: array
            items:
              $ref: '#/definitions/MaintenanceTaskResponse'
        required: false
        description: An array of MaintenanceTask objects. If no tasks were found in the query, this portion of the response doesn't exist.
      _links:
        type: object
        properties:
          tasks:
            type: object
            properties:
              href:
              type: string
              description: Hyperlink to the API endpoint that retrieves all tasks
              example: http://localhost:8080/api/tasks

  MaintenanceTask:
    type: object
    properties:
      id:
        type: integer
        description: The task ID
        example: 151
      deviceId:
        type: integer
        description: The ID of the device this task is tied to
        example: 4
      status:
        type: string
        description: The status of the task (OPEN or CLOSED)
        example: OPEN
      severity:
        type: string
        description: The severity of the task. UNIMPORTANT, IMPORTANT, or CRITICAL.
        example: CRITICAL
      description:
        type: string
        description: The description of the task
        example: Fix CPU overheating problem
      registered:
        type: string
        description: Datetime string, registration time for the task
        example: 2022-08-28T17:32:11.058674

  MaintenanceTaskResponse:
    type: object
    properties:
      schema:
        $ref: '#/definitions/MaintenanceTask'
      _links:
        type: object:
          schema:
            $ref: '#/definitions/MaintenanceTaskLinks'

  MaintenanceTaskLinks:
    type: object
      properties:
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  description: Hyperlink to this task
                  example: http://localhost:8080/api/tasks/733
            tasks:
              type: object
              properties:
                href:
                  type: string
                  description: Hyperlink to the API endpoint that retrieves all tasks
                  example: http://localhost:8080/api/tasks
basePath: /api
schemes:
  - http
  - https

paths:
  /tasks:
    parameters:
      - in: query
        name: deviceId
        type: integer
        description: The device by which to filter the tasks
        required: false
      - in: query
        name: status
        type: string
        description: The status by which to filter tasks (OPEN/CLOSED)
        required: false
      - in: query
        name: severity
        type: string
        description: The severity by which to filter tasks (UNIMPORTANT / IMPORTANT / CRITICAL)
        required: false
    get:
      summary: Returns a list of maintenance tasks, filtered according to query parameters
      produces: application/json
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/definitions/MaintenanceTaskListResponse'
        400:
          description: Bad request
    delete:
      summary: Delete all the tasks that match the query parameters. If no parameters are supplied, all tasks in the database are deleted.
      responses:
        200:
          description: OK
        400:
          description: Bad request
    post:
      summary: Creates a new maintenance task
      consumes: application/json
      parameters:
        - in: body
          name: Maintenance task
          schema:
            $ref: '#/definitions/MaintenanceTask'
          required:
            - deviceId
            - description
            - status
            - severity
      produces: application/json
      responses:
        201:
          description: CREATED
          content:
            application/json:
              schema:
                $ref: '#/definitions/MaintenanceTaskResponse'
        404:
          description: Factory device not found
        400:
          description: Bad request, error in body 

  /tasks/{taskId}:
    parameters:
      - in: path
        name: taskId
        required: true
        schema:
          type: integer
          minimum: 1
        description: The task ID 
    get:
      summary: Returns a single task based on the given ID
      produces: application/json 
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/definitions/MaintenanceTaskResponse'
        404:
          description: Task not found
        400:
          description: Bad request, taskId is not an integer
    patch:
      summary: Modifies the fields of a task based on the given ID
      parameters:
        - in: body
          name: MaintenanceTask
          description: The MaintenanceTask object to update
          schema:
            type: object
            properties:
              deviceId:
                type: integer
                required: false
                description: Factory Device ID
              severity:
                type: string
                required: false
                description: Task severity (UNIMPORTANT, IMPORTANT, or CRITICAL)
                example: "CRITICAL"
              status:
                type: string
                required: false
                description: Task status (OPEN or CLOSED)
                example: "OPEN"
              description:
                type: string
                required: false
                description: The task description
                example: "Reconnected RAM sticks on motherboard"
              registered:
                type: string
                required: false
                description: The date and time the task was registered. java.time.LocalDateTime format.
                example: "2022-08-29T15:10:06.042637"
      consumes: application/json
      produces: application/json
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/definitions/MaintenanceTaskResponse'
        404:
          description: Task not found
        404:
          description: Factory device not found
        400:
          description: Bad request, error in request body
        400:
          description: Bad request, taskId is not an integer
    delete:
      summary: Deletes the specified task
      produces: application/json
      responses:
        200:
          description: OK
        404:
          description: Task not found
        400:
          description: Bad request, taskId is not an integer
